call plug#begin('~/.vim/plugins')

Plug 'arcticicestudio/nord-vim'
Plug 'vim-airline/vim-airline'
Plug 'scrooloose/nerdtree'

call plug#end()

set number
set autoindent

set foldmethod=indent
nnoremap <silent> <Space> @=(foldlevel('.')?'za':"\<Space>")<CR>
vnoremap <Space> zf

let g:airline_powerline_fonts = 1
colorscheme nord
hi comment ctermfg=red

" stop writing .netrwhist:
let g:netrw_dirhistmax=0

" open NERDTree automatically if no files were specified for vim
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" open NERDTree automatically if a directory was specified to open:
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | exe 'cd '.argv()[0] | endif

" <CTRL> + b will open the NERDTree browser
map <C-b> :NERDTreeToggle<CR>
