call plug#begin('~/.vim/plugins')

Plug 'arcticicestudio/nord-vim'
Plug 'vim-airline/vim-airline'

call plug#end()

set number
set autoindent

set foldmethod=indent
nnoremap <silent> <Space> @=(foldlevel('.')?'za':"\<Space>")<CR>
vnoremap <Space> zf

let g:airline_powerline_fonts = 1
colorscheme nord
hi comment ctermfg=red

" stop writing .netrwhist:
let g:netrw_dirhistmax=0
