###################################################################################################
#           _                                                                                     #
#   _______| |__  _ __ ___                                                                        #
#  |_  / __| '_ \| '__/ __|                                                                       #
#   / /\__ \ | | | | | (__                                                                        #
#  /___|___/_| |_|_|  \___|                                                                       #
#                                                                                                 #
###################################################################################################


# Path to your oh-my-zsh installation.
export ZSH="${HOME}/.config/oh-my-zsh/"

# https://github.com/denysdovhan/spaceship-prompt
ZSH_THEME="spaceship"

SPACESHIP_DIR_COLOR=yellow
SPACESHIP_DIR_TRUNC=0
SPACESHIP_DIR_TRUNC_REPO=false

# disable any language support:
SPACESHIP_JULIA_SHOW=false
SPACESHIP_HASKELL_SHOW=false
SPACESHIP_RUST_SHOW=false
SPACESHIP_PHP_SHOW=false
SPACESHIP_GOLANG_SHOW=false
SPACESHIP_SWIFT_SHOW_LOCAL=false
SPACESHIP_XCODE_SHOW_LOCAL=false
SPACESHIP_ELIXIR_SHOW=false
SPACESHIP_ELM_SHOW=false
SPACESHIP_RUBY_SHOW=false
SPACESHIP_NODE_SHOW=false
SPACESHIP_PACKAGE_SHOW=false


# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=14

# Uncomment the following line if pasting URLs and other text is messed up.
DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Set a custom format using the strftime function format specifications.
HIST_STAMPS="dd.mm.yyyy"

# Load plugins, stored in $ZSH/plugins/
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
#if [[ -n $SSH_CONNECTION ]]; then
#  export TERM='vim'
#else
#  export EDITOR='mvim'
#fi

# Set personal aliases:
alias ssh="TERM=rxvt-16color ssh"
alias ip="ip -c"
